let vocab = 
+"<word> 見る (miru) : see, look at</word>"
+"<word> 多い (ooi) : a lot of, many</word>"
+"<word> 家 (ie) : home, household</word>"
+"<word> これ (kore) : this, this one</word>"
+"<word> それ (sore) : that, that one</word>"
+"<word> 私 (watashi) : I</word>"
+"<word> 仕事 (shigoto) : work, job</word>"
+"<word> いつ (itsu) : when</word>"
+"<word> する (suru) : do, make</word>"
+"<word> 出る (deru) : go out, leave</word>"
+"<word> 使う (tsukau) : use, make use of</word>"
+"<word> 所 (tokoro) : place</word>"
+"<word> 作る (tsukuru) : make, create</word>"
+"<word> 思う (omou) : think</word>"
+"<word> 持つ (motsu) : have, possess</word>"
+"<word> 買う (kau) : buy</word>"
+"<word> 時間 (jikan) : time, hour</word>"
+"<word> 知る (shiru) : know</word>"
+"<word> 同じ (onaji) : same, identical</word>"
+"<word> 今 (ima) : now</word>"
+"<word> 新しい (atarashii) : new</word>"
+"<word> なる (naru) : become</word>"
+"<word> まだ (mada) : (not) yet, still</word>"
+"<word> あと (ato) : after</word>"
+"<word> 聞く (kiku) : hear, ask</word>"
+"<word> 言う (iu) : say, tell</word>"
+"<word> 少ない (sukunai) : few, little</word>"
+"<word> 高い (takai) : high, tall</word>"
+"<word> 子供 (kodomo) : child</word>"
+"<word> そう (sou) : so, that way</word>"
+"<word> もう (mou) : already, yet</word>"
+"<word> 学生 (gakusei) : student</word>"
+"<word> 熱い (atsui) : hot (to touch)</word>"
+"<word> どうぞ (douzo) : please</word>"
+"<word> 午後 (gogo) : afternoon, p.m</word>"
+"<word> 長い (nagai) : long</word>"
+"<word> 本 (hon) : book, volume</word>"
+"<word> 今年 (kotoshi) : this year (colloquial)</word>"
+"<word> よく (yoku) : often, well</word>"
+"<word> 彼女 (kanojo) : she, one’s girlfriend</word>"
+"<word> どう (dou) : how, what</word>"
+"<word> 言葉 (kotoba) : word, language</word>"
+"<word> 顔 (kao) : face</word>"
+"<word> 終わる (owaru) : finish, end</word>"
+"<word> 一つ (hitotsu) : one (thing)</word>"
+"<word> あげる (ageru) : give, offer (colloquial)</word>"
+"<word> こう (kou) : like this, such</word>"
+"<word> 学校 (gakkou) : school</word>"
+"<word> くれる (kureru) : be given</word>"
+"<word> 始める (hajimeru) : start (something)</word>"
+"<word> 起きる (okiru) : get up, get out of bed</word>"
+"<word> 春 (haru) : spring</word>"
+"<word> 午前 (gozen) : morning, a.m</word>"
+"<word> 別 (betsu) : another, different</word>"
+"<word> どこ (doko) : where</word>"
+"<word> 部屋 (heya) : room</word>"
+"<word> 若い (wakai) : young</word>"
+"<word> 車 (kuruma) : car, automobile</word>"
+"<word> 置く (oku) : put, place </word>"
+"<word> 住む (sumu) : live, reside</word>"
+"<word> 働く (hataraku) : work</word>"
+"<word> 難しい (muzukashii) : difficult</word>"
+"<word> 先生 (sensei) : teacher</word>"
+"<word> 立つ (tatsu) : stand, rise</word>"
+"<word> 呼ぶ (yobu) : call, name</word>"
+"<word> 大学 (daigaku) : university, college</word>"
+"<word> 安い (yasui) : cheap, inexpensive</word>"
+"<word> もっと (motto) : more</word>"
+"<word> 帰る (kaeru) : go back home</word>"
+"<word> 分かる (wakaru) : understand</word>"
+"<word> 広い (hiroi) : wide, big</word>"
+"<word> 数 (suu) : number</word>"
+"<word> 近い (chikai) : near, close</word>"
+"<word> そこ (soko) : there</word>"
+"<word> 走る (hashiru) : run</word>"
+"<word> 入れる (ireru) : put in</word>"
+"<word> 教える (oshieru) : teach, tell</word>"
+"<word> 歩く (aruku) : walk, go on foot</word>"
+"<word> 会う (au) : meet</word>"
+"<word> 書く (kaku) : write</word>"
+"<word> 頭 (atama) : head</word>"
+"<word> 売る (uru) : sell</word>"
+"<word> 大好き (daisuki) : like (something) a lot</word>"
+"<word> 体 (karada) : body, physique</word>"
+"<word> 直ぐ (sugu) : at once, soon</word>"
+"<word> 飛ぶ (tobu) : fly</word>"
+"<word> とても (totemo) : very (colloquial)</word>"
+"<word> 誰 (dare) : who</word>"
+"<word> 好き (suki) : favorite, liked</word>"
+"<word> 読む (yomu) : read</word>"
+"<word> 次 (tsugi) : next</word>"
+"<word> あなた (anata) : you</word>"
+"<word> 飲む (nomu) : drink</word>"
+"<word> 古い (furui) : old</word>"
+"<word> 質問 (shitsumon) : question</word>"
+"<word> 今日 (kyou) : to</word>"
+"<word> 友達 (tomodachi) : friend, companion (colloquial)</word>"
+"<word> 早い (hayai) : early</word>"
+"<word> どれ (dore) : what, which</word>"
+"<word> 美しい (utsukushii) : beautiful</word>"
+"<word> いつも (itsumo) : always (colloquial)</word>"
+"<word> 足 (ashi) : leg, foot</word>"
+"<word> 起こす (okosu) : wake (someone) up</word>"
+"<word> 見せる (miseru) : show</word>"
+"<word> 娘 (musume) : daughter, girl</word>"
+"<word> 楽しむ (tanoshimu) : enjoy</word>"
+"<word> 色 (iro) : color</word>"
+"<word> みんな (minna) : everybody (colloquial)</word>"
+"<word> 取る (toru) : take, get</word>"
+"<word> 勉強 (benkyou) : study</word>"
+"<word> できる (dekiru) : can do, be good at</word>"
+"<word> 短い (mijikai) : short, brief</word>"
+"<word> 落ちる (ochiru) : fall, come down</word>"
+"<word> 息子 (musuko) : son</word>"
+"<word> 白い (shiroi) : white, blank</word>"
+"<word> 飛行機 (hikouki) : airplane</word>"
+"<word> 病気 (byouki) : illness</word>"
+"<word> 冬 (fuyu) : winter</word>"
+"<word> 年 (toshi) : year, age</word>"
+"<word> 重い (omoi) : heavy</word>"
+"<word> 胸 (mune) : chest, breast</word>"
+"<word> 払う (harau) : pay (money, respect, attention, etc</word>"
+"<word>)</word>"
+"<word> 軽い (karui) : light (of weight)</word>"
+"<word> 見つける (mitsukeru) : find</word>"
+"<word> 忘れる (wasureru) : forget, leave behind</word>"
+"<word> 酒 (sake) : alcohol, rice wine</word>"
+"<word> どちら (dochira) : which (polite)</word>"
+"<word> 姉 (ane) : (one’s own) older sister</word>"
+"<word> 覚える (oboeru) : memorize, learn</word>"
+"<word> 狭い (semai) : narrow, small</word>"
+"<word> 赤い (akai) : red</word>"
+"<word> 着る (kiru) : wear, put on</word>"
+"<word> 笑う (warau) : laugh, smile</word>"
+"<word> 一番 (ichiban) : most, best</word>"
+"<word> 授業 (juugyo) : class session, lecture</word>"
+"<word> 週 (shuu) : week</word>"
+"<word> 漢字 (kanji) : Chinese character</word>"
+"<word> 自転車 (jitensha) : bicycle</word>"
+"<word> 電車 (densha) : train</word>"
+"<word> 探す (sagasu) : search for, look for</word>"
+"<word> 紙 (kami) : paper</word>"
+"<word> 歌う (utau) : sing</word>"
+"<word> 遅い (osoi) : slow, late</word>"
+"<word> 首 (kubi) : neck</word>"
+"<word> 速い (hayai) : fast</word>"
+"<word> 一緒に (issho ni) : together, at the same time</word>"
+"<word> 今月 (kongetsu) : this month</word>"
+"<word> 遊ぶ (asobu) : play</word>"
+"<word> 遠い (tooi) : far, distant</word>"
+"<word> 弱い (yowai) : weak</word>"
+"<word> 耳 (mimi) : ear</word>"
+"<word> 座る (suwaru) : sit, sit down</word>"
+"<word> 右 (migi) : right</word>"
+"<word> 浴びる (abiru) : take (a shower)</word>"
+"<word> 肩 (kata) : shoulder</word>"
+"<word> 寝る (neru) : lie down and sleep, go to sleep</word>"
+"<word> 消す (kesu) : switch off, turn off</word>"
+"<word> 元気 (genki) : healthy, energetic</word>"
+"<word> 全部 (zenbu) : all, whole</word>"
+"<word> 去年 (kyonen) : last year (colloquial)</word>"
+"<word> 引く (hiku) : draw, pull</word>"
+"<word> 図書館 (toshokan) : library</word>"
+"<word> 上げる (ageru) : raise, lift</word>"
+"<word> 緑 (midori) : green</word>"
+"<word> 腕 (ude) : arm</word>"
+"<word> ドア (doa) : door (loan word)</word>"
+"<word> 女の子 (onna no ko) : little girl</word>"
+"<word> 男の子 (otoko no ko) : boy</word>"
+"<word> 私たち (watachitachi) : we (colloquial)</word>"
+"<word> 近く (chikaku) : near, close to</word>"
+"<word> やる (yaru) : do, give</word>"
+"<word> かなり (kanari) : fairly, rather</word>"
+"<word> 国 (kuni) : country</word>"
+"<word> 起こる (okoru) : happen</word>"
+"<word> 秋 (aki) : autumn, fall</word>"
+"<word> 送る (okuru) : send</word>"
+"<word> 死ぬ (shinu) : die</word>"
+"<word> 気持ち (kimochi) : feeling, sensation</word>"
+"<word> 乗る (noru) : ride, take </word>"
+"<word> いる (iru) : be present, stay</word>"
+"<word> 木 (ki) : tree, wood</word>"
+"<word> 開ける (akeru) : open, unlock (doors, windows, etc</word>"
+"<word>)</word>"
+"<word> 閉める (shimeru) : shut, close (doors, windows, etc</word>"
+"<word>)</word>"
+"<word> 続く (tsuzuku) : continue, follow</word>"
+"<word> お医者さん (oishasan) : doctor (polite)</word>"
+"<word> 円 (en) : Japanese yen</word>"
+"<word> ここ (koko) : here</word>"
+"<word> 待つ (matsu) : wait, wait for</word>"
+"<word> 低い (hikui) : low, short</word>"
+"<word> もらう (morau) : receive</word>"
+"<word> 食べる (taberu) : eat</word>"
+"<word> 兄 (ani) : (one’s own) older brother</word>"
+"<word> 名前 (namae) : name</word>"
+"<word> 夫 (otto) : husband</word>"
+"<word> 一 (ichi) : one</word>"
+"<word> 結婚 (kekkon) : marriage</word>"
+"<word> 親 (oya) : parent</word>"
+"<word> 話す (hanasu) : speak, talk</word>"
+"<word> 少し (sukoshi) : a bit, a little while</word>"
+"<word> 閉じる (tojiru) : shut, close (books, eyes, etc</word>"
+"<word>)</word>"
+"<word> 時 (toki) : time, moment</word>"
+"<word> 米 (kome) : rice (grain)</word>"
+"<word> 切る (kiru) : cut</word>"
+"<word> 楽しい (tanoshii) : fun, enjoyable</word>"
+"<word> 服 (fuku) : clothes (colloquial)</word>"
+"<word> 後ろ (ushiro) : back, behind</word>"
+"<word> 嬉しい (ureshii) : happy, glad</word>"
+"<word> 腰 (koshi) : waist, lower back</word>"
+"<word> 日曜日 (nichiyoubi) : Sun</word>"
+"<word> 昼 (hiru) : </word>"
+"<word> お母さん (okaasan) : mother (colloquial)</word>"
+"<word> 大学生 (daigakusei) : university student</word>"
+"<word> 終わり (owari) : end, conclusion</word>"
+"<word> 背 (se) : height, stature</word>"
+"<word> 手伝う (tetsudau) : help, assist</word>"
+"<word> 鼻 (hana) : nose</word>"
+"<word> 起きる (okiru) : occur, happen</word>"
+"<word> 載せる (noseru) : place, put on</word>"
+"<word> 悲しい (kanashii) : sad</word>"
+"<word> しゃべる (shaberu) : chat, talk</word>"
+"<word> 近く (chikaku) : in the near future, before long</word>"
+"<word> 甘い (amai) : sweet</word>"
+"<word> テーブル (te-buru) : table</word>"
+"<word> 食べ物 (tabemono) : food (colloquial)</word>"
+"<word> 始まる (hajimaru) : begin</word>"
+"<word> ゲーム (ge-mu) : game</word>"
+"<word> 十 (juu) : ten</word>"
+"<word> 天気 (tenki) : weather</word>"
+"<word> 暑い (atsui) : hot (of weather)</word>"
+"<word> 太い (futoi) : thick, fat</word>"
+"<word> 晩 (ban) : evening, night (from sunset to bedtime)</word>"
+"<word> 土曜日 (doyoubi) : Satur</word>"
+"<word> 痛い (itai) : sore, painful</word>"
+"<word> お父さん (otousan) : father, dad (colloquial)</word>"
+"<word> 多分 (tabun) : probably, perhaps</word>"
+"<word> 時計 (tokei) : clock, watch</word>"
+"<word> 泊まる (tomaru) : stay overnight</word>"
+"<word> どうして (doushite) : how come</word>"
+"<word> 掛ける (kakeru) : hang, put on </word>"
+"<word> 曲がる (magaru) : make a turn, turn</word>"
+"<word> お腹 (onaka) : stomach, belly</word>"
+"<word> ミーティング (mi-tingu) : meeting</word>"
+"<word> 嫌い (kirai) : dislike (habitual)</word>"
+"<word> 金曜日 (kinyoubi) : Fri</word>"
+"<word> 要る (iru) : need, require</word>"
+"<word> 無い (nai) : to not be</word>"
+"<word> 風邪 (kaze) : cold (illness)</word>"
+"<word> 黄色い (kiiro) : yellow</word>"
+"<word> 優しい (yasashii) : gentle, kind</word>"
+"<word> 晴れる (hareru) : be sunny, clear up</word>"
+"<word> 汚い (kitanai) : dirty</word>"
+"<word> 茶色 (chairo) : brown</word>"
+"<word> 空く (suku) : be empty, become less crowded</word>"
+"<word> 上る (noboru) : go up, climb</word>"
+"<word> ご飯 (gohan) : meal, cooked rice</word>"
+"<word> 日 (nichi) : counter for </word>"
+"<word> 髪の毛 (kaminoke) : hair, each single hair</word>"
+"<word> つける (tsukeru) : switch on, turn on</word>"
+"<word> 月曜日 (getsuyoubi) : Mon</word>"
+"<word> 入る (hairu) : enter</word>"
+"<word> カタカナ (katakana) : katakana</word>"
+"<word> 今週 (konshyu) : this week</word>"
+"<word> 開く (hiraku) : open (books, eyes, etc</word>"
+"<word>)</word>"
+"<word> 水 (mizu) : water</word>"
+"<word> あれ (are) : that (over there)</word>"
+"<word> 二 (nichi) : two</word>"
+"<word> 締める (shimeru) : tighten, fasten</word>"
+"<word> まずい (mazui) : bad (taste), distasteful</word>"
+"<word> 平仮名 (hiragana) : hiragana</word>"
+"<word> 曇る (kumoru) : become cloudy</word>"
+"<word> 触る (sawaru) : touch, feel</word>"
+"<word> 駄目 (dame) : no good</word>"
+"<word> 飲み物 (nomimono) : beverage, drink</word>"
+"<word> 木曜日 (mokuyoubi) : Thurs</word>"
+"<word> 曜日 (youbi) : </word>"
+"<word> そば (soba) : side, vicinity</word>"
+"<word> こっち (kochi) : here, this way (casual)</word>"
+"<word> 火曜日 (kayoubi) : Tues</word>"
+"<word> 渇く (kawaku) : be thirsty</word>"
+"<word> 三 (san) : three</word>"
+"<word> 水曜日 (suiyoubi) : Wednes</word>"
+"<word> 二つ (futatsu) : two (things)</word>"
+"<word> 今晩 (konban) : this evening, tonight</word>"
+"<word> 千 (sen) : thousand</word>"
+"<word> 六日 (muika) : six </word>"
+"<word> お姉さん (onesan) : older sister</word>"
+"<word> 直る (naoru) : be repaired, get fixed</word>"
+"<word> ちょっと (chotto) : just a moment, just a little</word>"
+"<word> 四 (yon) : four (Japanese origin)</word>"
+"<word> これから (korekara) : from now on, after this</word>"
+"<word> 考える (kankaeru) : think, consider</word>"
+"<word> 戻る (modoru) : return to a point of departure</word>"
+"<word> 変える (kaeru) : change (something), alter</word>"
+"<word> 朝 (asa) : morning</word>"
+"<word> 歯 (ha) : tooth</word>"
+"<word> 頑張る (ganbaru) : work hard, do one’s best</word>"
+"<word> 携帯電話 (keitaidenwa) : cellular phone</word>"
+"<word> 雨 (ame) : rain</word>"
+"<word> 金 (kane) : money (colloquial) </word>"
+"<word> 易しい (yasashi) : easy, simple (colloquial)</word>"
+"<word> お兄さん (onisan) : older brother</word>"
+"<word> 大きい (oki) : big</word>"
+"<word> 小さい (chisai) : small</word>"
+"<word> 辛い (karai) : spicy, hot</word>"
+"<word> 八 (hachi) : eight</word>"
+"<word> あそこ (asoko) : over there</word>"
+"<word> 来る (kuru) : come</word>"
+"<word> 前 (mae) : front, before</word>"
+"<word> 五日 (itsuka) : five </word>"
+"<word> いっぱい (ippai) : full</word>"
+"<word> 九 (kyu) : nine (used before counter words and in decimal places)</word>"
+"<word> 酸っぱい (suppai) : sour</word>"
+"<word> 違う (chigau) : differ, be wrong</word>"
+"<word> 細い (hosoi) : thin, slender</word>"
+"<word> 三つ (mitsu) : three (things)</word>"
+"<word> 八日 (youka) : eight </word>"
+"<word> 高校生 (kokosei) : high school student</word>"
+"<word> 上手 (jouzu) : good, skilled</word>"
+"<word> 強い (tsuyoi) : strong</word>"
+"<word> 七 (nana) : seven (Japanese origin)</word>"
+"<word> 二十日 (hatsuka) :  </word>"
+"<word> 左 (hidari) : left</word>"
+"<word> 二日 (futsuka) : two </word>"
+"<word> 四つ (yotsu) : four (things)</word>"
+"<word> 暖かい (atatakai) : warm</word>"
+"<word> ある (aru) : exist, there is</word>"
+"<word> いい (ii) : good (informal/spoken form)</word>"
+"<word> 上 (ue) : up, above</word>"
+"<word> 駅 (eki) : train station</word>"
+"<word> 美味しい (oishi) : tasty</word>"
+"<word> 昨日 (kino) : yester</word>"
+"<word> 綺麗 (kirei) : pretty, clean</word>"
+"<word> 五 (go) : five</word>"
+"<word> 九つ (kokonotsu) : nine (things)</word>"
+"<word> お願い (onegai) : favor</word>"
+"<word> 答える (kotaeru) : give an answer</word>"
+"<word> 先 (saki) : ahead, first</word>"
+"<word> 寒い (samui) : cold (temperature of the air)</word>"
+"<word> 四 (shi) : four (Chinese origin)</word>"
+"<word> 三日 (mikka) : three </word>"
+"<word> 下 (shita) : under, below</word>"
+"<word> 大丈夫 (daijoubu) : all right, OK</word>"
+"<word> 大人 (otona) : adult</word>"
+"<word> 出す (dasu) : take out</word>"
+"<word> 父 (chichi) : (speaker’s) father</word>"
+"<word> 母 (haha) : (speaker’s) mother</word>"
+"<word> 月 (tsuki) : moon</word>"
+"<word> 妹 (imouto) : younger sister</word>"
+"<word> 冷たい (tsumetai) : cold (to touch)</word>"
+"<word> 弟 (otouto) : younger brother</word>"
+"<word> 手 (te) : hand</word>"
+"<word> 十日 (tooka) : ten </word>"
+"<word> 口 (kuchi) : mouth</word>"
+"<word> 夏 (natsu) : summer</word>"
+"<word> 七つ (nanatsu) : seven (things)</word>"
+"<word> 時々 (tokidoki) : sometimes</word>"
+"<word> 何 (nani) : what</word>"
+"<word> 人 (hito) : person</word>"
+"<word> 一人 (hitori) : one person</word>"
+"<word> 一日 (tsuitachi) : first of the month</word>"
+"<word> 九日 (kokonoka) : nine </word>"
+"<word> 方 (hou) : direction, side</word>"
+"<word> 他 (hoka) : other (Japanese origin)</word>"
+"<word> 僕 (boku) : I, me (usually used by young males)</word>"
+"<word> 欲しい (hoshii) : want, desire (of the speaker)</word>"
+"<word> 万 (man) : ten thousand</word>"
+"<word> 見える (mieru) : be visible, can see</word>"
+"<word> 道 (michi) : street, way</word>"
+"<word> 五つ (itsutsu) : five (things)</word>"
+"<word> 目 (me) : eye</word>"
+"<word> 八つ (yattsu) : eight (things)</word>"
+"<word> 止める (tomeru) : stop, give up</word>"
+"<word> 四日 (yokka) : four </word>"
+"<word> 夜 (yoru) : night (from sunset to sunrise)</word>"
+"<word> 来年 (rainen) : next year</word>"
+"<word> 六 (roku) : six</word>"
+"<word> 悪い (warui) : bad</word>"
+"<word> お手洗い (otearai) : toilet, bathroom</word>"
+"<word> ご主人 (goshujin) : (someone else’s) husband</word>"
+"<word> 本当に (hontouni) : really, truly</word>"
+"<word> 自分 (jibun) : self, oneself</word>"
+"<word> ため (tame) : sake, purpose</word>"
+"<word> 見つかる (mitsukaru) : be found, be caught</word>"
+"<word> 休む (yasumu) : take a rest, take a break</word>"
+"<word> ゆっくり (yukkuri) : slowly</word>"
+"<word> 六つ (muttsu) : six (things)</word>"
+"<word> 花 (hana) : flower</word>"
+"<word> 動く (ugoku) : move</word>"
+"<word> 線 (sen) : line</word>"
+"<word> 七日 (nanoka) : seven </word>"
+"<word> 以外 (igai) : except for</word>"
+"<word> 男 (otoko) : man, male</word>"
+"<word> 彼 (kare) : he, one’s boyfriend</word>"
+"<word> 女 (onna) : woman</word>"
+"<word> 妻 (tsuma) : woman</word>"
+"<word> 百 (hyaku) : hundred</word>"
+"<word> 辺 (atari) : vicinity</word>"
+"<word> 店 (mise) : shop, store</word>"
+"<word> 閉まる (shimaru) : be shut, be closed</word>"
+"<word> 問題 (mondai) : problem, question</word>"
+"<word> 必要 (hitsuyou) : need, necessary</word>"
+"<word> もつ (motsu) : last long, be durable</word>"
+"<word> 開く (hiraku) : open</word>"
+"<word> 昨年 (sakunen) : last year (formal, often used in writing)</word>"
+"<word> 治る (naoru) : be cured, get well</word>"
+"<word> ドル (doru) : dollar</word>"
+"<word> システム (sisutemu) : system (loan word)</word>"
+"<word> 以上 (ijou) : more than, not less than</word>"
+"<word> 最近 (saikin) : recent, latest</word>"
+"<word> 世界 (sekai) : world</word>"
+"<word> コンピューター (konpyu-ta-) : computer</word>"
+"<word> やる (yaru) : give (to an inferior)</word>"
+"<word> 意味 (imi) : meaning, sense</word>"
+"<word> 増える (fueru) : increase, accrue</word>"
+"<word> 選ぶ (erabu) : choose, elect</word>"
+"<word> 生活 (seikatsu) : life, living</word>"
+"<word> 進める (susumeru) : go ahead, proceed</word>"
+"<word> 続ける (tsuzukeru) : continue, keep up</word>"
+"<word> ほとんど (hotondo) : almost, hardly</word>"
+"<word> 会社 (kaisha) : company, corporation</word>"
+"<word> 家 (ie) : house, dwelling</word>"
+"<word> 多く (ooku) : much, largely</word>"
+"<word> 話 (hanashi) : talk, story</word>"
+"<word> 上がる (agaru) : go up, rise (physical movement)</word>"
+"<word> もう (mou) : another, again</word>"
+"<word> 集める (atsumeru) : collect, gather</word>"
+"<word> 声 (koe) : voice, sound</word>"
+"<word> 初めて (hajimete ) : for the first time</word>"
+"<word> 変わる (kawaru) : change, turn into</word>"
+"<word> まず (mazu) : first of all, to begin with</word>"
+"<word> 社会 (shakai) : society</word>"
+"<word> プログラム (puroguramu) : program booklet</word>"
+"<word> 力 (chikara) : strength, power</word>"
+"<word> 今回 (konkai) : this time</word>"
+"<word> 予定 (yotei) : schedule, plan</word>"
+"<word> まま (mama) : as is, still (in the current state)</word>"
+"<word> テレビ (terebi) : television</word>"
+"<word> 減る (heru) : decrease, diminish</word>"
+"<word> 消える (kieru) : be extinguished, disappear</word>"
+"<word> 家族 (kazoku) : family, household</word>"
+"<word> 比べる (kuraberu) : compare, contrast</word>"
+"<word> 生まれる (umareru) : be born, come into existence</word>"
+"<word> ただ (tada) : free</word>"
+"<word> これら (korera) : these</word>"
+"<word> 調べる (shiraberu) : investigate, check</word>"
+"<word> 事故 (jiko) : accident, trouble</word>"
+"<word> 電話 (denwa) : telephone, phone call</word>"
+"<word> 外国 (gaikoku) : foreign country</word>"
+"<word> 銀行 (ginkou) : bank</word>"
+"<word> 十分 (juubun) : enough, plentiful</word>"
+"<word> あまり (amari) : (not) much</word>"
+"<word> 写真 (shashin) : photograph</word>"
+"<word> 繰り返す (kurikaesu) : repeat</word>"
+"<word> 種類 (shurui) : kind, type</word>"
+"<word> 意見 (iken) : opinion</word>"
+"<word> 新聞 (shinbun) : newspaper</word>"
+"<word> 文章 (bunshou) : sentence, writing</word>"
+"<word> 目立つ (medatsu) : stand out, be conspicuous</word>"
+"<word> 相手 (aite) : opponent, the other party</word>"
+"<word> 病院 (byouin) : hospital</word>"
+"<word> 厚い (atsui) : thick, bulky</word>"
+"<word> 忙しい (isogashii) : busy, occupied</word>"
+"<word> 薄い (usui) : thin, weak</word>"
+"<word> 川 (kawa) : river, stream</word>"
+"<word> 暗い (kurai) : dark, gloomy</word>"
+"<word> クラス (kurasu) : class (in school)</word>"
+"<word> 黒い (kuroi) : black, dark</word>"
+"<word> バス (basu) : bus</word>"
+"<word> 青い (aoi) : blue</word>"
+"<word> 買い物 (kaimono) : shopping, purchase</word>"
+"<word> 薬 (kusuri) : drug, medicine</word>"
+"<word> 砂糖 (satou) : sugar</word>"
+"<word> 休み (yasumi) : holi</word>"
+"<word> 郵便局 (yuubinkyoku) : post office</word>"
+"<word> 住所 (juusho) : address</word>"
+"<word> こちら (kochira) : here, this way (polite)</word>"
+"<word> 財布 (saifu) : purse, wallet</word>"
+"<word> パスポート (pasupo-to) : passport</word>"
+"<word> 椅子 (isu) : chair</word>"
+"<word> 可愛い (kawaii) : cute, sweet</word>"
+"<word> お祖父さん (ojiisan) : grandfather (colloquial)</word>"
+"<word> 切手 (kitte) : postage stamp</word>"
+"<word> 涼しい (suzushii) : cool (of temperature)</word>"
+"<word> いくつ (ikutsu) : how many, how old</word>"
+"<word> メニュー (menyu-) : menu</word>"
+"<word> 電気 (denki) : electricity, electric light</word>"
+"<word> 勝つ (katsu) : win</word>"
+"<word> 負ける (makeru) : lose</word>"
+"<word> 建てる (tateru) : build, erect</word>"
+"<word> 日記 (nikki) : diary</word>"
+"<word> 売り切れ (urikire) : sell out</word>"
+"<word> お巡りさん (omawarisan) : police officer (colloquial)</word>"
+"<word> 目覚まし時計 (mezamashitokei) : alarm clock</word>"
+"<word> レシート (reshi-to) : receipt (loan word)</word>"
+"<word> ティッシュ (tisshu) : tissue</word>"
+"<word> 歯ブラシ (haburashi) : toothbrush</word>"
+"<word> 下りる (oriru) : go down, come down</word>"
+"<word> 洗う (arau) : wash</word>"
+"<word> パート (pa-to) : part-time</word>"
+"<word> 氏名 (shimei) : full name</word>"
+"<word> 今夜 (konya) : tonight, this evening</word>"
+"<word> 夜中 (yonaka) : midnight</word>"
+"<word> 来週 (raishuu) : next week</word>"
+"<word> 誰か (dareka) : someone</word>"
+"<word> 何 (nani) : what</word>"
+"<word> 今朝 (kesa) : this morning</word>"
+"<word> 寿司 (sushi) : sushi</word>"
+"<word> 履く (haku) : put on (shoes), wear (pants, skirt)</word>"
+"<word> おじさん (ojisan) : uncle</word>"
+"<word> おばさん (obasan) : aunt</word>"
+"<word> お祖母さん (obaasan) : grandmother (colloquial)</word>"
+"<word> いとこ (itoko) : cousin</word>"
+"<word> 辞書 (jisho) : dictionary (category)</word>"
+"<word> 朝ご飯 (asagohan) : breakfast</word>"
+"<word> 白 (shiro) : white</word>"
+"<word> どっち (docchi) : which (casual)</word>"
+"<word> そっち (socchi) : there (casual)</word>"
+"<word> 明日 (ashita) : tomorrow (colloquial)</word>"
+"<word> 明後日 (myougonichi/asatte) : </word>"
+"<word> 一昨日 (ototoi) : the </word>"
+"<word> 庭 (niwa) : garden, yard</word>"
+"<word> 左側 (hidarigawa) : left side</word>"
+"<word> 右側 (migigawa) : right side</word>"
+"<word> 指 (yubi) : finger, toe</word>"
+"<word> 眼鏡 (megane) : glasses</word>"
+"<word> 鞄 (kaban) : bag, handbag</word>"
+"<word> あっち (acchi) : other side, over there (casual)</word>"
+"<word> 大人しい (otonashii) : gentle, quiet</word>"
+"<word> 下手 (heta) : not good at</word>"
+"<word> 厳しい (kibishii) : strict, severe</word>"
+"<word> 一人で (hitoride) : by oneself, alone</word>"
+"<word> 答え (kotae) : answer, solution</word>"
+"<word> この頃 (konogoro) : these </word>"
+"<word> 残念 (zannen) : regretful, disappointing</word>"
+"<word> 仕舞う (shimau) : put away, put in</word>"
+"<word> 心配 (shinpai) : anxiety, worry</word>"
+"<word> 外 (soto) : outside, open air</word>"
+"<word> 大切 (taisetsu) : important, valuable</word>"
+"<word> ちょうど (choudo) : just, exactly</word>"
+"<word> 助ける (tasukeru) : help, save</word>"
+"<word> 勤める (tsutomeru) : serve, hold a job</word>"
+"<word> 連れていく (tsureteiku) : take along, bring along (a person)</word>"
+"<word> 丈夫 (joubu) : healthy, sturdy</word>"
+"<word> 賑やか (nigiyaka) : lively, exciting</word>"
+"<word> 眠い (nemui) : sleepy</word>"
+"<word> 山 (yama) : mountain</word>"
+"<word> 橋 (hashi) : bridge</word>"
+"<word> 止まる (tomaru) : come to a stop, cease</word>"
+"<word> 降る (furu) : fall, come down (rain, snow, etc</word>"
+"<word>)</word>"
+"<word> 本当 (hontou) : reality, genuine</word>"
+"<word> 町 (machi) : town, city</word>"
+"<word> お菓子 (okashi) : sweets, snacks</word>"
+"<word> 緩い (yurui) : slack, loose</word>"
+"<word> 良い (yoi) : good (formal/written form)</word>"
+"<word> ようこそ (youkoso) : welcome (greeting)</word>"
+"<word> お土産 (omiyage) : souvenir (polite)</word>"
+"<word> 両親 (ryoushin) : parents</word>"
+"<word> ウェーター (we-ta-) : waiter</word>"
+"<word> ウェートレス (we-toresu) : waitress</word>"
+"<word> 絶対に (zettaini) : absolutely, definitely</word>"
+"<word> ごちそう (gochisou) : feast, treat</word>"
+"<word> フォーク (fo-ku) : fork</word>"
+"<word> スプーン (supu-n) : spoon</word>"
+"<word> 瓶 (bin) : bottle</word>"
+"<word> つく (tsuku) : be on, be switched on</word>"
+"<word> 醤油 (shouyu) : soy sauce</word>"
+"<word> 茶碗 (chawan) : rice bowl</word>"
+"<word> 決める (kimeru) : decide, agree upon</word>"
+"<word> 感じる (kanjiru) : feel, sense</word>"
+"<word> 生きる (ikiru) : live (one’s life)</word>"
+"<word> 動かす (ugokasu) : move (something)</word>"
+"<word> 壊れる (kowareru) : break, break down</word>"
+"<word> 復習 (fukushuu) : review</word>"
+"<word> 眉 (mayu) : eyebrow</word>"
+"<word> 客 (kyaku) : visitor, customer</word>"
+"<word> 机 (tsukue) : desk</word>"
+"<word> 風呂 (furo) : bath</word>"
+"<word> 湯 (yu) : hot water</word>"
+"<word> ぬるい (nurui) : tepid, lukewarm</word>"
+"<word> 風邪薬 (kazegusuri) : cold medicine</word>"
+"<word> 靴下 (kutsushita) : socks</word>"
+"<word> たばこ (tabako) : tobacco, cigarette</word>"
+"<word> アイスコーヒー (aisuko-hi-) : iced coffee</word>"
+"<word> 天ぷら (tempura) : Japanese deep-fried food</word>"
+"<word> 肉 (niku) : flesh, meat</word>"
+"<word> 昨夜 (sakuya) : last night, last evening (colloquial)</word>"
+"<word> 流行る (hayaru) : be in fashion, be popular</word>"
+"<word> 連れて来る (tsuretekuru) : bring (a person)</word>"
+"<word> 方 (kata) : person (polite form)</word>"
+"<word> 零 (rei) : zero</word>"
+"<word> 雲 (kumo) : cloud</word>"
+"<word> 空 (sora) : sky</word>"
+"<word> 人気 (ninki) : popularity</word>"
+"<word> 兄さん (niisan) : (one’s own) older brother (polite)</word>"
+"<word> 姉さん (neesan) : (one’s own) older sister (polite)</word>"
+"<word> 平成 (heisei) : Heisei era</word>"
+"<word> 毎月 (maitsuki) : every month</word>"
+"<word> 半日 (hannichi) : half a </word>"
+"<word> 半月 (hantsuki) : half a month</word>"
+"<word> なるほど (naruhodo) : I see, really</word>"
+"<word> つまり (tsumari) : in short, that is to say</word>"
+"<word> そのまま (sonomama) : as it is, just like that</word>"
+"<word> はっきり (hakkiri) : clearly</word>"
+"<word> 大変 (taihen) : awful, hard</word>"
+"<word> 簡単 (kantan) : simple, easy</word>"
+"<word> 似ている (niteiru) : look like, resemble</word>"
+"<word> 驚く (odoroku) : be surprised, be startled</word>"
+"<word> 嫌 (iya/ kira-i) : dislike (situational)</word>"
+"<word> 喧嘩 (kenka) : fight, argument</word>"
+"<word> 遅れる (okureru) : be late</word>"
+"<word> にんじん (ninjin) : carrot</word>"
+"<word> ジャガイモ (jagaimo) : potato</word>"
+"<word> ナス (nasu) : eggplant</word>"
+"<word> やかん (yakan) : kettle</word>"
+"<word> 話し合う (hanashiau) : discuss, talk over</word>"
+"<word> 残す (nokosu) : leave, leave undone</word>"
+"<word> ごちそうする (gochisousuru) : treat, host (a meal)</word>"
+"<word> 合う (au) : fit, match</word>"
+"<word> 当たる (ataru) : (go straight and) hit, strike</word>"
+"<word> 集まる (atsumaru) : gather, be collected</word>"
+"<word> 場所 (basho) : place, space</word>"
+"<word> 海 (umi) : sea, ocean</word>"
+"<word> 少年 (shounen) : boy (between  and  years old)</word>"
+"<word> 孫 (mago) : grandchild</word>"
+"<word> 生徒 (seito) : pupil, student</word>"
+"<word> 高校 (koukou) : high school (for short)</word>"
+"<word> 年上 (toshiue) : older, senior</word>"
+"<word> 卒業 (sotsugyou) : graduation</word>"
+"<word> 運動 (undou) : movement, exercise</word>"
+"<word> 選手 (senshu) : athlete, (sports) player</word>"
+"<word> 映画 (eiga) : movie</word>"
+"<word> 英語 (eigo) : English</word>"
+"<word> 手紙 (tegami) : letter</word>"
+"<word> 動物 (doubutsu) : animal</word>"
+"<word> 音 (oto) : sound, noise</word>"
+"<word> 海外 (kaigai) : overseas, abroad</word>"
+"<word> 外国人 (gaikokujin) : foreigner</word>"
+"<word> 帰国 (kikoku) : return to one’s country</word>"
+"<word> 彼ら (karera) : they</word>"
+"<word> 機械 (kikai) : machine</word>"
+"<word> 基本 (kihon) : basics</word>"
+"<word> 今度 (kondo) : this time, next time</word>"
+"<word> 最後 (saigo) : last</word>"
+"<word> 最初 (saikin) : first, outset</word>"
+"<word> 準備 (junbi) : preparation, arrangement</word>"
+"<word> 進む (susumu) : advance, move forward</word>"
+"<word> 直接 (chokugo) : directly</word>"
+"<word> 特に (tokuni) : specially, particularly</word>"
+"<word> 届く (todoku) : reach, be received</word>"
+"<word> なぜ (naze) : why</word>"
+"<word> 並ぶ (narabu) : line up, be parallel</word>"
+"<word> 運ぶ (hakobu) : carry, transport</word>"
+"<word> 直す (naosu) : repair, fix</word>"
+"<word> 反対 (hantai) : oppose, object</word>"
+"<word> 場合 (baai) : situation, case</word>"
+"<word> 詳しい (kuwashii) : detailed</word>"
+"<word> いたずら (itazura) : mischief, prank</word>"
+"<word> お祝い (oiwai) : celebrate</word>"
+"<word> くし (kushi) : comb</word>"
+"<word> こぼれる (koboreru) : spill, overflow</word>"
+"<word> 伝える (tsutaeru) : convey, transmit</word>"
+"<word> 膝 (hiza) : knee</word>"
+"<word> 肘 (hiji) : elbow</word>"
+"<word> 枕 (makura) : pillow</word>"
+"<word> 建物 (tatemono) : building, structure</word>"
+"<word> 道路 (douro) : road</word>"
+"<word> 四つ角 (yotsukado) : intersection</word>"
+"<word> 曲がり角 (magarikado) : corner (to turn)</word>"
+"<word> 警察 (keisatsu) : police</word>"
+"<word> 空気 (kuuki) : air, atmosphere</word>"
+"<word> スポーツ (supo-tsu) : sport</word>"
+"<word> チャンス (chansu) : chance</word>"
+"<word> クリーニング (kuri-ningu) : dry cleaning</word>"
+"<word> サービス (sa-bisu) : service, on the house</word>"
+"<word> グループ (guru-bu) : group</word>"
+"<word> 自宅 (jitaku) : one’s house, one’s home</word>"
+"<word> 家庭 (katei) : home, family</word>"
+"<word> 期間 (kikan) : term, period</word>"
+"<word> 年度 (nendo) : year, school year</word>"
+"<word> 経験 (keiken) : experience, knowledge</word>"
+"<word> 安全 (anzen) : safety, security</word>"
+"<word> 危険 (kiken) : danger, dangerous</word>"
+"<word> 注意 (chuui) : attention, care</word>"
+"<word> 成功 (seikou) : success</word>"
+"<word> 努力 (doryoku) : endeavor, effort</word>"
+"<word> 説明 (setsumei) : explanation, description</word>"
+"<word> 地震 (jishin) : earthquake</word>"
+"<word> 手術 (shujutsu) : surgical operation</word>"
+"<word> 火傷 (yakedo) : burn</word>"
+"<word> 課題 (kadai) : task, assignment</word>"
+"<word> 子 (ko) : young child, kid</word>"
+"<word> 確認 (kakunin) : confirmation</word>"
+"<word> 実際 (jissai) : reality, actual state</word>"
+"<word> 国際 (kokusai) : international (used in compound nouns)</word>"
+"<word> 会議 (kaigi) : conference, meeting</word>"
+"<word> 提案 (teian) : proposition, proposal</word>"
+"<word> 事務所 (jimusho) : office, one’s place of business</word>"
+"<word> 教授 (kyouju) : professor</word>"
+"<word> 世紀 (seki) : century</word>"
+"<word> あちこち (achikochi) : all over, here and there</word>"
+"<word> そちら (sochira) : there, that way (polite)</word>"
+"<word> あちら (achira) : over there, that way (polite)</word>"
+"<word> もし (moshi) : if, in case of</word>"
+"<word> うるさい (urusai) : noisy, annoying</word>"
+"<word> 固い (katai) : stiff, tight</word>"
+"<word> 深い (fukai) : deep, profound</word>"
+"<word> 面白い (omoshiroi) : interesting, amusing</word>"
+"<word> 全く (mattaku) : entirely, truly</word>"
+"<word> 半分 (hanbun) : half</word>"
+"<word> 普通 (futsuu) : normal, regular</word>"
+"<word> 分 (bun) : amount, share</word>"
+"<word> 文化 (bunka) : culture</word>"
+"<word> 毎日 (mainichi) : every </word>"
+"<word> 気を付ける (kiwotsukeru) : be careful about, pay attention to</word>"
+"<word> 守る (mamoru) : protect, observe</word>"
+"<word> もちろん (mochiron) : of course</word>"
+"<word> やはり (yahari) : as expected</word>"
+"<word> いくら (ikura) : how much (money)</word>"
+"<word> よろしく (yoroshiku) : one’s regards </word>"
+"<word> どなた (donata) : who (polite)</word>"
+"<word> 許す (yurusu) : permit, forgive</word>"
+"<word> 分ける (wakeru) : divide, share</word>"
+"<word> 自然 (shizen) : nature</word>"
+"<word> アパート (apa-to) : apartment, flat</word>"
+"<word> ホテル (hoteru) : hotel</word>"
+"<word> パソコン (pasokon) : personal computer</word>"
+"<word> うまい (umai) : good at</word>"
+"<word> 明るい (akarui) : bright, cheerful</word>"
+"<word> 急ぐ (isogu) : hurry, do quickly</word>"
+"<word> 歌 (uta) : song</word>"
+"<word> 中学校 (chuugakkou) : junior high school</word>"
+"<word> テスト (tesuto) : test</word>"
+"<word> ポスト (posuto) : postbox, mailbox</word>"
+"<word> ハンカチ (hankachi) : handkerchief</word>"
+"<word> 髪 (kami) : hair, hairstyle</word>"
+"<word> 帽子 (boushi) : hat, cap</word>"
+"<word> 被る (kaburu) : wear, put on (on one’s head)</word>"
+"<word> ブラウス (burausu) : blouse</word>"
+"<word> 週末 (shuumatsu) : weekend</word>"
+"<word> 先週 (senshuu) : last week</word>"
+"<word> 再来週 (saraishuu) : the week after next</word>"
+"<word> いつか (itsuka) : some time, some </word>"
+"<word> 宿題 (mondai) : homework</word>"
+"<word> 鍵 (kagi) : key, lock</word>"
+"<word> 傘 (kasa) : umbrella, parasol</word>"
+"<word> 乗り換える (norikaeru) : change, transfer</word>"
+"<word> 向かう (mukau) : face, head toward</word>"
+"<word> 本屋 (honya) : bookstore (colloquial)</word>"
+"<word> お茶 (ocha) : tea (polite)</word>"
+"<word> 改札口 (kaisatsuguchi) : ticket gate</word>"
+"<word> 晴れ (hare) : fine weather, clear sky</word>"
+"<word> バス停 (basutei) : bus stop</word>"
+"<word> 曇り (kumori) : cloudy weather</word>"
+"<word> 塩 (shio) : salt</word>"
+"<word> たくさん (takusan) : a lot, in large quantity</word>"
+"<word> 大嫌い (daikirai) : hate</word>"
+"<word> 中 (naka) : inside, middle</word>"
+"<word> 二階 (nikai) : second floor, upstairs</word>"
+"<word> 無くす (nakusu) : lose, get rid of</word>"
+"<word> まあまあ (maamaa) : OK, not bad</word>"
+"<word> 黄色 (kiiro) : yellow color</word>"
+"<word> ランチ (ranchi) : lunch (loan word)</word>"
+"<word> 魚 (sakana) : fish</word>"
+"<word> 味 (aji) : taste, flavor</word>"
+"<word> りんご (ringo) : apple</word>"
+"<word> みかん (mikan) : tangerine</word>"
+"<word> 皿 (sara) : plate, counter (for plates or helpings)</word>"
+"<word> コーヒー (ko-hi-) : coffee</word>"
+"<word> コップ (koppu) : cup, glass</word>"
+"<word> 二人 (futari) : two persons</word>"
+"<word> 止む (yamu) : stop, cease</word>"
+"<word> 九 (kyuu) : nine</word>"
+"<word> 昼間 (hiruma) : </word>"
+"<word> いつ頃 (itsugoro) : about when, about what time</word>"
+"<word> 字 (ji) : (individual) character, letter</word>"
+"<word> 七 (nana) : seven (Chinese origin)</word>"
+"<word> お釣り (otsuri) : change (of money)</word>"
+"<word> 名字 (myouji) : surname, family name</word>"
+"<word> おじ (oji) : (one’s own) uncle</word>"
+"<word> おば (oba) : (one’s own) aunt</word>"
+"<word> 祖父 (sofu) : grandfather (formal)</word>"
+"<word> 祖母 (sobo) : grandmother (formal)</word>"
+"<word> 大事 (daiji) : importance</word>"
+"<word> 見方 (mikata) : view, perspective</word>"
+"<word> 鳥 (tori) : bird, poultry</word>"
+"<word> 犬 (inu) : dog</word>"
+"<word> 返事 (henji) : view, perspective</word>"
+"<word> また (mata) : again, also, or</word>"
+"<word> 年間 (nenkan) : period of one year</word>"
+"<word> 青 (ao) : blue, green</word>"
+"<word> 赤 (aka) : red color</word>"
+"<word> 信号 (shingou) : signal, traffic light</word>"
+"<word> 円 (en) : circle</word>"
+"<word> 非常に (hijouni) : very, extremely</word>"
+"<word> 複雑 (fukuzatsu) : complicated, intricate</word>"
+"<word> 平和 (heiwa) : peace, harmony</word>"
+"<word> 回る (mawaru) : turn round, go around</word>"
+"<word> 若者 (wakamono) : young person, youth</word>"
+"<word> 雪 (yuki) : snow, snowfall</word>"
+"<word> うまい (umai) : sweet, delicious</word>"
+"<word> 思い出す (omoidasu) : recollect, recall</word>"
+"<word> 聞こえる (kikoeru) : hear, be heard</word>"
+"<word> 借りる (kariru) : borrow</word>"
+"<word> 返す (kaesu) : return, repay</word>"
+"<word> 受け取る (uketoru) : receive, get</word>"
+"<word> 捨てる (suteru) : discard, abandon</word>"
+"<word> 一緒 (issho) : together, same (colloquial)</word>"
+"<word> 遊び (asobi) : play, amusement</word>"
+"<word> 移す (utsusu) : move, transfer</word>"
+"<word> 大きさ (ookisa) : size, dimension</word>"
+"<word> 考え (kangae) : thought, idea</word>"
+"<word> 空港 (kuukou) : airport (for public transportation)</word>"
+"<word> 出発 (shuppatsu) : departure, starting</word>"
+"<word> 地図 (chizu) : map, atlas</word>"
+"<word> 運転 (unten) : drive</word>"
+"<word> 降りる (oriru) : get off, land</word>"
+"<word> ガス (gasu) : gas (loan word)</word>"
+"<word> 必ず (hanarazu) : without exception, always</word>"
+"<word> カメラ (kamera) : camera</word>"
+"<word> 通う (kayou) : go to and from, frequent a place</word>"
+"<word> 急に (kyuuni) : suddenly, unexpectedly</word>"
+"<word> サラリーマン (sarari-man) : office worker, company employee</word>"
+"<word> 給料 (kyuuryou) : salary, pay</word>"
+"<word> 曲 (kyoku) : piece of music</word>"
+"<word> 切れる (kireru) : cut well, be sharp</word>"
+"<word> 正しい (tadashii) : correct, righteous</word>"
+"<word> 苦しい (kurushii) : painful, agonizing</word>"
+"<word> 細かい (komakai) : minute, fine</word>"
+"<word> 静か (shizuka) : quiet, tranquil</word>"
+"<word> 健康 (kenkou) : health</word>"
+"<word> ゴルフ (gorufu) : golf</word>"
+"<word> コース (ko-su) : course, route</word>"
+"<word> 頼む (tanomu) : order, ask for</word>"
+"<word> 困る (komaru) : be in trouble, not know what to do</word>"
+"<word> ずっと (zutto) : all the time, all through</word>"
+"<word> 例えば (tatoeba) : for example</word>"
+"<word> つもり (tsumori) : intention, purpose</word>"
+"<word> しばらく (shibaraku) : a little while, a while</word>"
+"<word> 紹介 (shoukai) : introduction</word>"
+"<word> 小学校 (shougakkou) : elementary school</word>"
+"<word> 公園 (kouen) : park, public garden</word>"
+"<word> 中学 (chuugaku) : junior high</word>"
+"<word> 成績 (seiseki) : results, grade</word>"
+"<word> 教科書 (kyoukasho) : textbook, schoolbook</word>"
+"<word> 席 (seki) : seat, one’s place</word>"
+"<word> 教室 (kyoushitsu) : classroom, class</word>"
+"<word> 教師 (kyoushi) : teacher, instructor</word>"
+"<word> 試験 (shiken) : exam</word>"
+"<word> 合格 (goukaku) : pass an examination</word>"
+"<word> 数学 (suugaku) : mathematics</word>"
+"<word> 数字 (suuji) : numeric characters</word>"
+"<word> 音楽 (ongaku) : music</word>"
+"<word> 食事 (shokuji) : meal</word>"
+"<word> 壁 (kabe) : wall, partition</word>"
+"<word> 信じる (shinjiru) : believe, trust</word>"
+"<word> 育てる (sodateru) : bring up, raise</word>"
+"<word> 倒れる (taoreru) : fall over</word>"
+"<word> 落とす (otosu) : drop</word>"
+"<word> 代わる (kawaru) : substitute, be substituted for</word>"
+"<word> タクシー (takushi-) : taxi</word>"
+"<word> 確か (tashika) : for sure, for certain</word>"
+"<word> 立てる (tateru) : stand, set up</word>"
+"<word> 中学生 (chuugakusei) : junior high school student</word>"
+"<word> 売れる (ureru) : sell, be in demand</word>"
+"<word> 着く (tsuku) : arrive at, reach</word>"
+"<word> 決まる (kimaru) : be decided</word>"
+"<word> 飾る (kazaru) : decorate</word>"
+"<word> 殺す (korosu) : kill</word>"
+"<word> 下げる (sageru) : lower, turn down</word>"
+"<word> 贈る (okuru) : offer, give</word>"
+"<word> 訪ねる (tazuneru) : visit, go to see</word>"
+"<word> 打つ (utsu) : hit, strike</word>"
+"<word> 相談 (soudan) : consultation, advice</word>"
+"<word> 玄関 (genkan) : entrance, door</word>"
+"<word> 兄弟 (kyoudai) : sibling</word>"
+"<word> 長男 (chounan) : eldest son</word>"
+"<word> 高さ (takasa) : height</word>"
+"<word> 用 (you) : things to do</word>"
+"<word> 時代 (jidai) : age, era</word>"
+"<word> 位置 (ichi) : position, location</word>"
+"<word> 季節 (kisetsu) : season</word>"
+"<word> 穴 (ana) : hole</word>"
+"<word> 裏 (ura) : the back, the reverse side</word>"
+"<word> 島 (shima) : island (Japanese origin)</word>"
+"<word> 海岸 (kaigan) : seashore, coast</word>"
+"<word> ガラス (garasu) : glass (material)</word>"
+"<word> 自然 (shizen) : natural</word>"
+"<word> 風 (kaze) : wind</word>"
+"<word> 科学 (kagaku) : science</word>"
+"<word> 太陽 (taiyou) : sun</word>"
+"<word> 台風 (taifuu) : typhoon</word>"
+"<word> 北 (kita) : north</word>"
+"<word> 馬 (uma) : horse</word>"
+"<word> 牛肉 (gyuuniku) : beef</word>"
+"<word> 雑誌 (zasshi) : magazine, journal</word>"
+"<word> 小説 (shousetsu) : novel</word>"
+"<word> 大使館 (taishikan) : embassy</word>"
+"<word> 故障 (koshou) : malfunction, breakdown</word>"
+"<word> 温度 (ondo) : temperature</word>"
+"<word> 何か (nanika) : something, some</word>"
+"<word> 向こう (mukou) : over there, on the other side</word>"
+"<word> 真ん中 (mannaka) : center, middle (casual)</word>"
+"<word> 遠く (tooku) : far away, at a distance</word>"
+"<word> 横 (yoko) : side, width across</word>"
+"<word> つまらない (tsumaranai) : boring, dull</word>"
+"<word> 素晴らしい (subarashii) : excellent, wonderful</word>"
+"<word> 毎年 (maitoshi/ mainen) : every year (colloquial)</word>"
+"<word> 来月 (raigetsu) : next month</word>"
+"<word> 日時 (nichiji) : date and time</word>"
+"<word> 夕方 (yuugata) : early evening, at dusk</word>"
+"<word> 通る (tooru) : pass, go through</word>"
+"<word> 自動車 (jidousha) : automobile</word>"
+"<word> 慣れる (nareru) : grow accustomed to, get used to</word>"
+"<word> 撮る (toru) : take (a photograph), film</word>"
+"<word> やっと (yatto) : at last, finally</word>"
+"<word> どんどん (dondon) : knock, bang</word>"
+"<word> 並べる (naraberu) : line up, arrange</word>"
+"<word> 逃げる (nigeru) : escape, run away</word>"
+"<word> 渡す (watasu) : hand over, give</word>"
+"<word> 値段 (nedan) : price</word>"
+"<word> 両方 (ryouhou) : both</word>"
+"<word> 約束 (yakusoku) : promise, vow</word>"
+"<word> 一部 (ichibu) : part</word>"
+"<word> ラジオ (rajio) : radio</word>"
+"<word> 入院 (nyuuin) : be hospitalized</word>"
+"<word> ニュース (nyu-su) : news</word>"
+"<word> 旅行 (ryokou) : travel, trip</word>"
+"<word> 用意 (youi) : preparation</word>"
+"<word> 伸びる (nobiru) : stretch, grow</word>"
+"<word> パーティー (pa-ti-) : party</word>"
+"<word> ビール (bi-ru) : beer</word>"
+"<word> 早く (hayaku) : early, soon</word>"
+"<word> 番組 (bangumi) : program</word>"
+"<word> ビデオ (bideo) : video</word>"
+"<word> 増やす (fuyasu) : increase</word>"
+"<word> 振る (furu) : wave, shake</word>"
+"<word> 迎える (mukaeru) : welcome, receive (a visitor)</word>"
+"<word> 無理 (muri) : unreasonable, impossible</word>"
+"<word> 珍しい (mezurashii) : rare, scarce</word>"
+"<word> 有名 (yuumei) : famous</word>"
+"<word> 喜ぶ (yorokobu) : be happy, be delighted</word>"
+"<word> 留学 (ryuugaku) : study abroad</word>"
+"<word> 料理 (ryouri) : cooking</word>"
+"<word> 野菜 (yasai) : vegetable</word>"
+"<word> 分かれる (wakareru) : be divided, split off</word>"
+"<word> 特別 (tokubetsu) : special</word>"
+"<word> 理由 (riyuu) : reason, excuse</word>"
+"<word> 自由 (jiyuu) : freedom</word>"
+"<word> 方向 (houkou) : direction, course</word>"
+"<word> 残る (nokoru) : remain, be left over</word>"
+"<word> ビル (biru) : building</word>"
+"<word> まとめる (matomeru) : gather together, put in order</word>"
+"<word> 流れる (nagareru) : flow, run</word>"
+"<word> セーター (se-ta-) : sweater</word>"
+"<word> シャツ (shatsu) : shirt</word>"
+"<word> 洗濯 (sentaku) : laundry, washing</word>"
+"<word> 間違える (machigaeru) : make a mistake, fail at</word>"
+"<word> アイスクリーム (aisukuri-mu) : ice cream</word>"
+"<word> 乾く (kawaku) : become dry </word>"
+"<word> 冷める (sameru) : cool off</word>"
+"<word> 色々 (iroiro) : a variety of</word>"
+"<word> 持って行く (motteiku) : take, bring</word>"
+"<word> 着替える (kigaeru) : change clothes</word>"
+"<word> 石鹸 (sekken) : soap</word>"
+"<word> 野球 (yakyuu) : baseball</word>"
+"<word> 昼食 (chyuushoku) : lunch</word>"
+"<word> 朝食 (choushoku) : breakfast</word>"
+"<word> 眠る (nemuru) : sleep, lie idle</word>"
+"<word> 初め (hajime) : beginning</word>"
+"<word> 火 (hi) : fire, flame</word>"
+"<word> 西 (nishi) : west, western</word>"
+"<word> 東 (higashi) : east, eastern</word>"
+"<word> 南 (minami) : south</word>"
+"<word> 夕食 (yuushoku) : supper, dinner</word>"
+"<word> なかなか (nakanaka) : rather, pretty</word>"
+"<word> 励ます (hagemasu) : encourage, cheer up</word>"
+"<word> 涙 (namida) : tear</word>"
+"<word> 夢 (yume) : dream</word>"
+"<word> 職場 (shokuba) : place of work, office</word>"
+"<word> 隣 (tonari) : next to, next door</word>"
+"<word> マンション (manshon) : apartment, residential building</word>"
+"<word> エレベーター (erebe-ta-) : elevator</word>"
+"<word> 窓 (mado) : window</word>"
+"<word> 押す (osu) : push, press down</word>"
+"<word> 入学 (nyuugaku) : enter a school, matriculate</word>"
+"<word> 戸 (to) : door, sliding door</word>"
+"<word> 通り (toori) : street, road</word>"
+"<word> 亡くなる (nakunaru) : die, pass away</word>"
+"<word> 夫婦 (fuufu) : husband and wife, married couple</word>"
+"<word> 女性 (josei) : woman, female (formal)</word>"
+"<word> 森 (mori) : forest</word>"
+"<word> トラック (torakku) : truck</word>"
+"<word> レコード (reko-do) : record</word>"
+"<word> 熱 (netsu) : heat, fever</word>"
+"<word> ページ (pe-ji) : page</word>"
+"<word> 踊る (odoru) : dance</word>"
+"<word> 長さ (nagasa) : length</word>"
+"<word> 厚さ (atsusa) : thickness</word>"
+"<word> 秘密 (himitsu) : secret, privacy</word>";
